# Logistic Regression

The old cost function for linear regression: $J_{\theta} = \frac{1}{m}\sum_{1}^{m}\cdot\frac{1}{2}\cdot(h_{\theta}(x^{(i)}) - y^{(i)})^2$

The new predictor: $h_{\theta}(x^{(i)}) = \frac{1}{1 + e^{-\theta^T{x(i)}}}$

The problem is with the new predictor $J_{\theta}$ is no longer convex and thus we can't optimize it.

### Cross Entropy Loss to the Rescue

$$cost(h_{\theta}(x),y)= \left\{   \begin{array}{lr}        -log(h_{\theta}(x)) & y= 1 \\       -log(1 - h_{\theta}(x)) & y = 0       \end{array}\right.$$

We can solve this with gradient descent.

$$\theta_{j} := \theta_{j} - \alpha\frac{\partial{J}}{\partial\theta_{j}}J_{\theta}$$

Where the partial is $$\frac{\partial{J}}{\partial\theta_{j}} = \frac{1}{m}\sum_{i=1}^m(h_{\theta}(x^i) - y^i)*x^i_j$$

In [121]:
import pandas as pd

In [123]:
data = pd.read_csv("scaled.csv")
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
    data.drop("species", axis=1), data.species)

In [117]:
def cross_entropy_loss(y_pred,target):
    return -np.mean((target*np.log1p(y_pred)+(1-target)*np.log1p(1-y_pred)))

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [145]:
theta = np.zeros(X.shape[1])
print("Shape of Theta is",theta.shape)
b = np.random.uniform(0,1,1)
print("Shape of Bias is",b.shape)

lr = 0.01
for _ in range(10000):
    prediction = sigmoid(X_train @ theta + b)
    partial = (prediction - y_train) @ X_train
    theta = theta - lr * partial / len(X)
    b = b - lr * np.average((prediction - y_train))
    if _ % 1000 == 0:
        loss = cross_entropy_loss(prediction,y_train)
        print(loss)

Shape of Theta is (5,)
Shape of Bias is (1,)
-0.40533835228160126
-0.6093892227291978
-0.6243484815786483
-0.6373224454584687
-0.6434093684684531
-0.6479876550348936
-0.6516164524430617
-0.6545972699829699
-0.6571096294795261
-0.6592685019644605


In [149]:
theta.values

array([-0.10852882,  1.34387704,  2.7596249 , -0.93766553, -1.37828092])

In [150]:
b

array([3.08004389])

In [151]:
preds = sigmoid(X_test @ theta + b)
pred = preds.round()

In [152]:
from sklearn.metrics import log_loss

In [153]:
log_loss(y_test,preds)

0.04815177027265223

In [141]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        14

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



# A Better way to implement Logistic Regression

In [142]:
from sklearn.linear_model import LogisticRegression

In [154]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
preds = clf.predict(X_test)
print(classification_report(y_test,preds))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        14

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [148]:
clf.coef_

array([[-1.1015082 , -0.11353864,  0.03322429, -0.24616217, -0.26087297]])

In [156]:
cross_entropy_loss(preds,y_test)

-0.6931471805599451

In [155]:
log_loss(y_test,preds)

9.992007221626415e-16